spring:
  liquibase:
    enabled: true
  datasource:
#    url: jdbc:mysql://localhost:8889/jcrent?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:postgresql://localhost:5432/jc_rent
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.fomichev.jc_rent: DEBUG

jwt:
  token:
    secret: M01SaUN2aU5SV1djOGk2M2FPMXZTa0pkM3hCMDFGMFM=
    expired: 3600000

notifications:
  email:
    sender: jc_rent@gmail.com