spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:8889/local_db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    com.fomichev.september: DEBUG

jwt:
  token:
    secret: september
    expired: 3600000