spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/jc_rent
    username: postgres
    password: changeit
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  token:
    secret: M01SaUN2aU5SV1djOGk2M2FPMXZTa0pkM3hCMDFGMFM=
    expired: 3600000

notifications:
  email:
    sender: jc_rent@gmail.com